# Generated by Django 3.2.7 on 2021-09-13 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(blank=True, choices=[('CRT', 'Current'), ('SVG', 'Savings')], default='CRT', max_length=10, null=True)),
                ('acc_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('acc_created', models.DateTimeField(auto_now_add=True)),
                ('acc_last_updated', models.DateTimeField(auto_now=True)),
                ('acc_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
