# Generated by Django 3.2.7 on 2021-09-20 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('acc_balance', models.FloatField(blank=True, default=0, null=True)),
                ('acc_created', models.DateTimeField(auto_now_add=True)),
                ('acc_last_updated', models.DateTimeField(auto_now=True)),
                ('acc_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_current_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('acc_balance', models.FloatField(blank=True, default=0, null=True)),
                ('acc_created', models.DateTimeField(auto_now_add=True)),
                ('acc_last_updated', models.DateTimeField(auto_now=True)),
                ('acc_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_savings_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_acc_balance_at', models.FloatField(blank=True, default=0, null=True)),
                ('tr_hash', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('tr_type', models.CharField(blank=True, choices=[('WTD', 'Withdrawal'), ('DEP', 'Deposit')], default='CRT', max_length=10, null=True)),
                ('tr_value', models.FloatField(blank=True, null=True)),
                ('tr_created', models.DateTimeField(auto_now_add=True)),
                ('tr_caccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_account_transactions', to='main.currentaccount')),
                ('tr_saccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_account_transactions', to='main.savingsaccount')),
                ('tr_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
