# Generated by Django 3.2.7 on 2021-09-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
