# Generated by Django 3.2.7 on 2021-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccount',
            name='acc_overdraft_limit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
