# Generated by Django 3.2.7 on 2021-09-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_acc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_hash', models.CharField(blank=True, choices=[('CRT', 'Current'), ('SVG', 'Savings')], default='CRT', max_length=10, null=True)),
                ('tr_type', models.CharField(blank=True, choices=[('WTD', 'Withdrawal'), ('DEP', 'Deposit')], default='CRT', max_length=10, null=True)),
                ('tr_value', models.FloatField(blank=True, null=True)),
                ('tr_created', models.DateTimeField(auto_now_add=True)),
                ('tr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='main.account')),
            ],
        ),
    ]
